### ISSUE TITLE
Transform error

### ISSUE THREAD

**Issue by hector** [osxi/node-try#3]
I am getting a transform error:

```TransformError: app/node_modules/node-try/dist/index.js: Couldn't find preset "es2015" relative to directory "app/node_modules/node-try```

I have the impression this is due to "babel-preset-es2015" missing as a dependency in package.json. In this case, other dependencies as lodash would be also missing.

**Comment by osxi** [comment]
@hector Yeah I don't think that preset existed at the time!

**Comment by osxi** [comment]
@hector Yeah a lot of stuff has changed with Babel since the writing of this package. The dependencies definitely need to be updated.

**Comment by osxi** [comment]
Looks like I was able to get this working on my machine inside of a vanilla node project so I'm going to close this issue. Feel free to re-open if it still happens.

I have updated some of the dependencies and will publish a new version (v0.3.0) with those changes.

**Comment by hector** [comment]
I am quite sure it still happens. You need to add babel-preset-es2015 as a dependency of the package, not as a devDependency
